config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :rooms
  resources :cities
  resources :users
  resources :hotels
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "hotels#index"
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  belongs_to :city
  has_many :reservations, dependent: :destroy
  has_many :users, through: :reservations
  has_many :rooms, through: :reservations
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  def index
    @hotels = Hotel.all
  end

  def show
  end

  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @hotel.destroy!

    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_hotel
    @hotel = Hotel.find(params[:id])
  end

  def hotel_params
    params.require(:hotel).permit(:name, :city, :about)
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel) do |form| %>
  <% if hotel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.number_field :city %>
  </div>

  <div>
    <%= form.label :about, style: "display: block" %>
    <%= form.text_area :about %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>">
  <p>
    <strong>Name:</strong>
    <%= hotel.name %>
  </p>

  <p>
    <strong>City:</strong>
    <%= hotel.city %>
  </p>

  <p>
    <strong>About:</strong>
    <%= hotel.about %>
  </p>

</div>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Show this hotel", @hotel %> |
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hotels</h1>
<div> </div>
<div id="hotels">
  <% @hotels.each do |hotel| %>
    <%= render hotel %>
    <p>
      <%= link_to "Show this hotel", hotel %>
    </p>
  <% end %>
</div>

<%= link_to "New hotel", new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hotel %>

<div>
  <%= link_to "Edit this hotel", edit_hotel_path(@hotel) %> |
  <%= link_to "Back to hotels", hotels_path %>

  <%= button_to "Destroy this hotel", @hotel, method: :delete %>
</div>